### PR TITLE
Switched from Nette\Object to Nette\SmartObject - PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by kratkyzobak**
Due to PHP 7.2 compatibility of package switched from Nette\Object to Nette\SmartObject

Addresses https://github.com/drahak/Restful/issues/135

Note: package is still depndend on drahak\OAuth2, which uses Nette\Object, so using OAuth2 auth handler still does not work in PHP 7.2. All other features work.

### CODE REVIEW

**Comment by kratkyzobak** [comment]
There were failed checks due to old version of Nette for PHP 5.4 & PHP 5.5. If support is needed, I would recomend use another branch, or composer version.

**Comment by hantc** [comment]
@kratkyzobak hello, is there a way how to get this specific branch via composer?

**Comment by jaroslavrehorka** [comment]
What happened to PHP7 branch? There is no such branch in this repo...

**Comment by drahak** [comment]
I renamed it to dev. There are some failing tests for older PHP versions I need to resolve before merging it into the main branch.

**Comment by namo-R** [comment]
Progress ? ;)

**Comment by tprochazka** [comment]
@drahak Weird. It was merged to PHP7 branch, and you told that it was renamed to dev. But when I check dev branch, it still use Nette/Object.

**Comment by MartinMystikJonas** [comment]
@drahak Any progress here? Can I do anything to help with PHP 7.2 compatibility? This issue blocked our upgrade to PHP7.2.

**Pull request merged**
